2020-04-29 16:29:30,365 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 136, in post
    user = current_app.config["User"]
KeyError: 'User'
2020-04-29 16:29:35,980 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 136, in post
    user = current_app.config["User"]
KeyError: 'User'
2020-04-29 16:30:33,760 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 140, in post
    user = current_app.config["User"]
KeyError: 'User'
2020-04-29 16:32:28,557 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 140, in post
    user = current_app.config["User"]
KeyError: 'User'
2020-04-29 16:34:14,339 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 140, in post
    return jsonify(code=4103, msg="请填写name或passwd")
KeyError: 'User'
2020-04-29 16:34:27,131 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 142, in post
    if {'name': name, 'passwd': str_md5(password)} not in user:
TypeError: argument of type 'MethodViewType' is not iterable
2020-04-29 16:35:13,888 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 142, in post
    if {'name': name, 'passwd': str_md5(password)} not in User:
TypeError: argument of type 'MethodViewType' is not iterable
2020-04-29 16:36:24,264 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 142, in post
TypeError: argument of type 'MethodViewType' is not iterable
2020-04-29 16:36:31,974 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 144, in post
    if {'name': name, 'passwd': str_md5(password)} not in User:
TypeError: argument of type 'MethodViewType' is not iterable
2020-04-29 16:37:30,927 - ERROR - app.py - log_exception - app - 1892 - Exception on /user/login [POST]
Traceback (most recent call last):
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/njcx/pyenv3_soc/lib/python3.7/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/njcx/peppa_soc_f/app/user/views.py", line 144, in post
    if {'name': name, 'passwd': str_md5(password)} not in user:
TypeError: argument of type 'MethodViewType' is not iterable
